"""
pipeline/tests/test_centroids.py

Tests for centroids.json generated by pipeline/scripts/build_centroids.py.
Also tests the pipeline/news/centroids.py lazy-load module (created in Wave 1;
tests that depend on it skip if the module is not yet present).
"""
from __future__ import annotations

import json
import pathlib

import pytest

REPO_ROOT = pathlib.Path(__file__).parent.parent.parent
CENTROIDS_PATH = REPO_ROOT / "data" / "incidents" / "centroids.json"

# ---------------------------------------------------------------------------
# Tests on generated centroids.json file
# ---------------------------------------------------------------------------


def test_centroids_file_exists():
    assert CENTROIDS_PATH.exists(), f"centroids.json not found at {CENTROIDS_PATH}"


def test_centroids_count():
    data = json.loads(CENTROIDS_PATH.read_text(encoding="utf-8"))
    assert len(data) == 346, f"Expected 346 entries, got {len(data)}"


def test_santiago_within_bounds():
    data = json.loads(CENTROIDS_PATH.read_text(encoding="utf-8"))
    santiago = data.get("13101")
    assert santiago is not None, "13101 (Santiago) not found in centroids.json"
    assert -34 < santiago["lat"] < -33, f"Santiago lat out of range: {santiago['lat']}"
    assert -71 < santiago["lng"] < -70, f"Santiago lng out of range: {santiago['lng']}"


def test_all_centroids_within_chilean_bounds():
    data = json.loads(CENTROIDS_PATH.read_text(encoding="utf-8"))
    for cut, v in data.items():
        lat, lng = v["lat"], v["lng"]
        # Chilean bounds: mainland south to ~-56, Antarctic territory to ~-90;
        # north to -17; Easter Island at ~-110 lng; mainland east to ~-65
        assert -90 < lat < -17, f"CUT {cut} lat={lat} outside Chilean bounds"
        assert -110 < lng < -65, f"CUT {cut} lng={lng} outside Chilean bounds"


def test_centroids_have_float_values():
    data = json.loads(CENTROIDS_PATH.read_text(encoding="utf-8"))
    for cut, v in data.items():
        assert isinstance(v["lat"], (int, float)), f"CUT {cut} lat is not numeric"
        assert isinstance(v["lng"], (int, float)), f"CUT {cut} lng is not numeric"


# ---------------------------------------------------------------------------
# Tests on pipeline.news.centroids module (Wave 1 — skip if not yet present)
# ---------------------------------------------------------------------------

try:
    import pipeline.news.centroids as centroids_mod  # type: ignore
    _MODULE_AVAILABLE = True
except ImportError:
    _MODULE_AVAILABLE = False


@pytest.mark.skipif(not _MODULE_AVAILABLE, reason="pipeline.news.centroids not yet implemented (Wave 1)")
def test_valid_cut_returns_latlon(monkeypatch, tmp_path):
    data = {"13101": {"lat": -33.456, "lng": -70.654}, "2101": {"lat": -18.5, "lng": -70.3}}
    centroid_file = tmp_path / "centroids.json"
    centroid_file.write_text(json.dumps(data), encoding="utf-8")

    monkeypatch.setattr(centroids_mod, "_CENTROIDS", None)
    monkeypatch.setattr(centroids_mod, "_CENTROID_PATH", centroid_file)
    lat, lng = centroids_mod.get_centroid("13101")
    assert abs(lat - (-33.456)) < 0.001
    assert abs(lng - (-70.654)) < 0.001


@pytest.mark.skipif(not _MODULE_AVAILABLE, reason="pipeline.news.centroids not yet implemented (Wave 1)")
def test_unknown_cut_returns_none(monkeypatch, tmp_path):
    data = {"13101": {"lat": -33.456, "lng": -70.654}}
    centroid_file = tmp_path / "centroids.json"
    centroid_file.write_text(json.dumps(data), encoding="utf-8")

    monkeypatch.setattr(centroids_mod, "_CENTROIDS", None)
    monkeypatch.setattr(centroids_mod, "_CENTROID_PATH", centroid_file)
    result = centroids_mod.get_centroid("99999")
    assert result is None
