#!/usr/bin/env python3
"""
pipeline/backfill_classifier_outage.py

NREC-09 (Phase 34-05): reclassify the news items lost to the Granite delisting
(V-04). From 2026-09-04T20:13:49Z every classifier call failed and the pipeline
recorded the item in data/incidents/rejected/YYYY-MM.json with stage
"classifier_none". record_rejected stored exactly the classifier inputs (title +
description[:500]), so no refetch is needed.

Pattern: pipeline/repair_sexual_family.py (argparse CLI, local repair first,
idempotent re-runs). R2 is regenerated by dispatching r2-archive.yml (credentials
stay in Actions), so there is NO --r2 flag here.

Two phases:
  --classify   calls the hardened 34-02 router (build_router_from_env → preflight →
               classify) and appends one JSON line per attempt to --cache (outside
               data/). It NEVER writes under data/, so it cannot race the news cron.
  --apply      reads the cache (last line per id wins) and rewrites data/incidents:
               accepted rows are merged (dedup 0.82 against existing incidents, then
               merge_and_write(..., bump_last_new=False) — G-07(a)/R-02) and removed
               from rejected/; the rest get their real stage. Idempotent: a second
               run changes no file.
Read-only modes: --dry-run, --review, --audit-sample N (G-11 / G-14 stratified sample).

Selection (G-06): rows with rejection_stage == "classifier_none" and
datetime(first_seen) >= --since (PARSED datetimes: a string compare drops the 16
rows at "2026-09-04T20:13:49.524591+00:00"), month files >= the --since month,
deduped by id (first occurrence wins). Order (G-11/R-07): dates 2026-09-05..09-22
ascending first, then everything else by date descending — so a spend-cap stop
still covers the uncovered September days.

Exit codes:
  0 = done (classify: loop finished, every selected id has a final outcome or an
      API_ERROR that the next run retries)
  1 = error (bad input, merge validation failure, missing key)
  2 = usage error (argparse)
  3 = spend cap reached (G-11) — cache intact, --apply works on the partial cache
  4 = router exhausted (router.classify returned None, BF-04) — re-invoke later;
      NEVER audit or apply after an exit 4
  5 = --audit-sample: a defined stratum has 0 candidates (stratum definition
      broken, BF-03) — STOP, do not sample around it

Usage:
  python pipeline/backfill_classifier_outage.py --dry-run --cache SCR/bf-cache.jsonl
  python pipeline/backfill_classifier_outage.py --classify --cache C --spend-cap USD \
      [--spend-ledger L] [--limit N]
  python pipeline/backfill_classifier_outage.py --review --cache C
  python pipeline/backfill_classifier_outage.py --audit-sample 50 --seed 3405 --cache C \
      --out SCR/bf-audit.jsonl [--withhold-ids FILE] [--exclude-ids ID,ID]
  python pipeline/backfill_classifier_outage.py --apply --cache C [--exclude-ids ID,ID] \
      [--withhold-ids FILE] [--report R] [--spend-ledger L]
"""
from __future__ import annotations

import argparse
import contextlib
import datetime as dt
import json
import logging
import math
import os
import pathlib
import random
import re
import sys
from collections import Counter
from typing import Callable, Iterable
from urllib.parse import urlparse

# NOTE (R-12): NOTHING from pipeline.news.classifier may be imported at module top.
# The classifier builds its import-time compat client from os.environ, so it must be
# imported only AFTER main() has loaded the .env files. All pipeline imports below
# are function-local for the same reason (and to keep --dry-run light).

_REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

logger = logging.getLogger("backfill_classifier_outage")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_DATA_DIR = _REPO_ROOT / "data" / "incidents"
DEFAULT_SINCE = "2026-09-04T20:13:49Z"
# Max first_seen of the 2,073 rows measured 2026-09-22 (the frozen audit subset).
FROZEN_MAX_FIRST_SEEN = "2026-09-22T20:49:36.848245+00:00"
# G-11 / R-07: the uncovered September days, classified first.
PRIORITY_START = dt.date(2026, 9, 5)
PRIORITY_END = dt.date(2026, 9, 22)
WINDOW_DAYS = 30  # store.merge_and_write default

STAGE_SELECTED = "classifier_none"

FINAL_OUTCOMES = {"ok", "not_crime", "parse_error"}
API_ERROR = "api_error"

# Spend meter prices, USD per 1M tokens.
# OpenRouter primary (G-16 winner deepseek/deepseek-v4.1-flash): catalog MAX over its
# endpoints, 34-AB-RESULTS.json candidates[0].pricing in_max / out_max (conservative).
OPENROUTER_MAX_IN = 0.375
OPENROUTER_MAX_OUT = 1.5
# DeepSeek direct backup: always the peak price (R-12), 34-AB-RESULTS.json backup.pricing.
DEEPSEEK_PEAK_IN = 0.30
DEEPSEEK_PEAK_OUT = 1.20
CHECKPOINT_EVERY = 50
OPENROUTER_KEY_URL = "https://openrouter.ai/api/v1/key"

# R-06 widened by NB-10 (kinship terms).
REVIEW_RE = re.compile(
    r"Fierro|Carahue|suicid|quit\w* la vida|abuel|suegr|sobrin|cuñad|hijo|hija|padre|"
    r"madre|herman|espos|pareja|yerno|nuera|accidente|choque|colisi|atropell|cárcel|"
    r"recinto penitenciario|interno|México|Argentina|España|Venezuela|Estados Unidos|"
    r"EE\.UU\.",
    re.IGNORECASE,
)

# G-11 / BF-03 strata (disjoint, assigned in priority order).
STRATUM_GNEWS = "gnews_title_only"
STRATUM_NON_CHILE = "non_chile_cue"
STRATUM_RANDOM = "random"
STRATA = (STRATUM_GNEWS, STRATUM_NON_CHILE, STRATUM_RANDOM)
NON_CHILE_RE = re.compile(
    r"México|Argentina|España|Venezuela|Estados Unidos|EE\.UU\.|EEUU|Perú|Bolivia|"
    r"Colombia|Ecuador|Brasil",
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------

def parse_dt(value: str | None) -> dt.datetime | None:
    """ISO datetime → aware UTC datetime. A trailing "Z" is normalized; a naive value
    is treated as UTC. Returns None when unparseable."""
    if not isinstance(value, str) or not value.strip():
        return None
    s = value.strip()
    if s.endswith(("Z", "z")):
        s = s[:-1] + "+00:00"
    try:
        parsed = dt.datetime.fromisoformat(s)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=dt.timezone.utc)
    return parsed.astimezone(dt.timezone.utc)


def _parse_date(value: str | None) -> dt.date | None:
    try:
        return dt.date.fromisoformat((value or "")[:10])
    except ValueError:
        return None


def _iso_z(moment: dt.datetime) -> str:
    return moment.astimezone(dt.timezone.utc).isoformat().replace("+00:00", "Z")


def _detect_eol(path: pathlib.Path) -> str:
    """Line ending of an existing file; LF for a new file (data/incidents is LF in git)."""
    try:
        return "\r\n" if b"\r\n" in path.read_bytes() else "\n"
    except FileNotFoundError:
        return "\n"


def eol_preserving_write_json(path: pathlib.Path, data, compact: bool = False) -> None:
    """Atomic JSON write that keeps the file's existing line ending.

    Same format as pipeline.shared.atomic_write.atomic_write_json (indent=2,
    ensure_ascii=False, no trailing newline), but written as BYTES: Path.write_text
    translates "\\n" to CRLF on Windows, which would flip every line of the LF files
    under data/incidents when this tool is run locally (Task 3 apply)."""
    eol = _detect_eol(path)
    trailing = False
    if path.exists():
        trailing = path.read_bytes().endswith(b"\n")
    if compact:
        text = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    else:
        text = json.dumps(data, ensure_ascii=False, indent=2)
    if trailing:
        text += "\n"
    if eol != "\n":
        text = text.replace("\n", eol)
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".tmp")
    tmp.write_bytes(text.encode("utf-8"))
    os.replace(tmp, path)


@contextlib.contextmanager
def _store_writes_preserve_eol():
    """Route pipeline.news.store's atomic writes through the EOL-preserving writer
    for the duration of the apply (scoped; the shared util is left untouched because
    the local CEAD scraper's CRLF outputs depend on its current behaviour)."""
    from pipeline.news import store

    original = store.atomic_write_json
    store.atomic_write_json = eol_preserving_write_json
    try:
        yield
    finally:
        store.atomic_write_json = original


def _assert_outside(path: pathlib.Path | None, data_dir: pathlib.Path, flag: str) -> None:
    if path is None:
        return
    p = path.resolve()
    d = data_dir.resolve()
    if p == d or d in p.parents:
        raise SystemExit(f"ERROR: {flag} {path} must be outside the data dir {data_dir}")


def _read_ids_file(path: pathlib.Path | None) -> set[str]:
    if path is None:
        return set()
    ids: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            ids.add(line)
    return ids


def _split_ids(value: str | None) -> set[str]:
    if not value:
        return set()
    return {part.strip() for part in value.split(",") if part.strip()}


# ---------------------------------------------------------------------------
# Selection (G-06)
# ---------------------------------------------------------------------------

def _month_files(data_dir: pathlib.Path, since: dt.datetime) -> list[pathlib.Path]:
    rejected_dir = data_dir / "rejected"
    if not rejected_dir.is_dir():
        return []
    since_month = since.strftime("%Y-%m")
    return [
        p for p in sorted(rejected_dir.glob("[0-9][0-9][0-9][0-9]-[0-9][0-9].json"))
        if p.stem >= since_month
    ]


def _load_envelope(path: pathlib.Path) -> dict:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict) or not isinstance(data.get("items"), list):
        raise ValueError(f"{path}: not a rejected envelope")
    return data


def _is_selected(row: dict, since: dt.datetime) -> bool:
    if row.get("rejection_stage") != STAGE_SELECTED:
        return False
    first_seen = parse_dt(row.get("first_seen"))
    return first_seen is not None and first_seen >= since


def _scan(data_dir: pathlib.Path, since: dt.datetime) -> list[tuple[str, dict]]:
    """(file name, row) of every selected row, deduped by id (first occurrence wins)."""
    out: list[tuple[str, dict]] = []
    seen_ids: set[str] = set()
    for path in _month_files(data_dir, since):
        for row in _load_envelope(path)["items"]:
            if not isinstance(row, dict) or not _is_selected(row, since):
                continue
            rid = row.get("id")
            if not rid or rid in seen_ids:
                continue
            seen_ids.add(rid)
            out.append((path.name, row))
    return out


def _order_key(row: dict):
    d = _parse_date(row.get("date")) or dt.date.min
    tie = (row.get("first_seen") or "", row.get("id") or "")
    if PRIORITY_START <= d <= PRIORITY_END:
        return (0, d.toordinal(), *tie)
    return (1, -d.toordinal(), *tie)


def select_outage_rows(data_dir: pathlib.Path, since: dt.datetime | str = DEFAULT_SINCE) -> list[dict]:
    """Outage rows, datetime-parsed, deduped by id, month files >= the since month.

    ORDERED (G-11/R-07): dates 2026-09-05..2026-09-22 ascending first, then the rest
    by date descending."""
    since_dt = parse_dt(since) if isinstance(since, str) else since
    if since_dt is None:
        raise ValueError(f"invalid since: {since!r}")
    rows = [row for _, row in _scan(pathlib.Path(data_dir), since_dt)]
    return sorted(rows, key=_order_key)


def _frozen(row: dict) -> bool:
    fs = parse_dt(row.get("first_seen"))
    return fs is not None and fs <= parse_dt(FROZEN_MAX_FIRST_SEEN)


# ---------------------------------------------------------------------------
# Cache
# ---------------------------------------------------------------------------

def load_cache(path: pathlib.Path) -> dict[str, dict]:
    """Last line per id wins. Missing file → {}. A torn last line is ignored."""
    cache: dict[str, dict] = {}
    if not path.exists():
        return cache
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                logger.warning("cache: skipping a malformed line")
                continue
            if isinstance(rec, dict) and rec.get("id"):
                cache[rec["id"]] = rec
    return cache


def _is_final(rec: dict | None) -> bool:
    return bool(rec) and rec.get("outcome") in FINAL_OUTCOMES


def _cache_line(key: str, res, now: dt.datetime) -> dict:
    output = res.output.model_dump() if res.output is not None else None
    return {
        "id": key,
        "outcome": getattr(res.outcome, "value", res.outcome),
        "status_code": res.status_code,
        "error": res.error,
        "output": output,
        "provider": res.provider,
        "model": res.model,
        "served_by": getattr(res, "served_by", None),
        "usage": getattr(res, "usage", None),
        "ts": _iso_z(now),
    }


# ---------------------------------------------------------------------------
# Spend meter (G-11, R-12)
# ---------------------------------------------------------------------------

class SpendMeter:
    """Provider-reported OpenRouter spend (GET /api/v1/key data.usage delta) with a
    ClassifyResult.usage fallback; DeepSeek-direct calls always at the peak price.

    total = measured OpenRouter delta at the last good checkpoint
          + OpenRouter estimates since that checkpoint
          + DeepSeek estimates (never measured).
    The /key usage is per key, so concurrent spend on the same key (e.g. the live cron)
    is counted too — conservative."""

    def __init__(
        self,
        cap: float,
        ledger_path: pathlib.Path | None,
        *,
        api_key: str | None = None,
        http_get: Callable | None = None,
        checkpoint_every: int = CHECKPOINT_EVERY,
        or_prices: tuple[float, float] = (OPENROUTER_MAX_IN, OPENROUTER_MAX_OUT),
        ds_prices: tuple[float, float] = (DEEPSEEK_PEAK_IN, DEEPSEEK_PEAK_OUT),
        next_call_ceiling: float | None = None,
    ):
        self.cap = float(cap)
        self.ledger_path = ledger_path
        self.api_key = api_key
        self._http_get = http_get
        self.checkpoint_every = checkpoint_every
        self.or_prices = or_prices
        self.ds_prices = ds_prices
        if next_call_ceiling is None:
            # One classify() may, on a breaker trip, re-dispatch a 5-item streak to
            # the backup (6 calls), and an empty answer is re-called once (x2).
            per_call = (5000 * max(or_prices[0], ds_prices[0])
                        + 512 * max(or_prices[1], ds_prices[1])) / 1e6
            next_call_ceiling = 6 * 2 * per_call
        self.next_call_ceiling = next_call_ceiling
        self.start_usage: float | None = None
        self.last_usage: float | None = None
        self.or_measured = 0.0
        self.or_estimate_since_checkpoint = 0.0
        self.ds_estimate = 0.0
        self.calls = 0
        self.checkpoints = 0
        self.measured_checkpoints = 0

    # -- provider-reported usage ------------------------------------------------
    def _fetch_usage(self) -> float | None:
        if not self.api_key:
            return None
        try:
            import requests

            get = self._http_get or requests.get
            resp = get(
                OPENROUTER_KEY_URL,
                headers={"Authorization": f"Bearer {self.api_key}"},
                timeout=15,
            )
            if getattr(resp, "status_code", None) != 200:
                return None
            usage = (resp.json().get("data") or {}).get("usage")
            if isinstance(usage, bool) or not isinstance(usage, (int, float)):
                return None
            return float(usage)
        except Exception as exc:  # noqa: BLE001 — fall back to estimates
            logger.warning("spend meter: /key usage unavailable (%s)", type(exc).__name__)
            return None

    def start(self) -> None:
        self.start_usage = self._fetch_usage()
        self.last_usage = self.start_usage
        self.persist()

    def checkpoint(self) -> None:
        self.checkpoints += 1
        if self.start_usage is None:
            return
        usage = self._fetch_usage()
        if usage is None:
            return
        self.last_usage = usage
        self.or_measured = max(0.0, usage - self.start_usage)
        self.or_estimate_since_checkpoint = 0.0
        self.measured_checkpoints += 1

    # -- estimates ----------------------------------------------------------------
    def estimate(self, res) -> float:
        usage = getattr(res, "usage", None) or {}
        pt = usage.get("prompt_tokens") or 0
        ct = usage.get("completion_tokens") or 0
        mult = 2 if getattr(res, "error", None) == "empty_content" else 1
        if getattr(res, "provider", None) == "deepseek":
            return mult * (pt * self.ds_prices[0] + ct * self.ds_prices[1]) / 1e6
        cost = usage.get("cost")
        if isinstance(cost, (int, float)) and not isinstance(cost, bool):
            return mult * float(cost)
        return mult * (pt * self.or_prices[0] + ct * self.or_prices[1]) / 1e6

    def charge(self, res) -> None:
        cost = self.estimate(res)
        if getattr(res, "provider", None) == "deepseek":
            self.ds_estimate += cost
        else:
            self.or_estimate_since_checkpoint += cost
        self.calls += 1
        if self.checkpoint_every and self.calls % self.checkpoint_every == 0:
            self.checkpoint()
        self.persist()

    @property
    def total(self) -> float:
        return self.or_measured + self.or_estimate_since_checkpoint + self.ds_estimate

    def would_exceed(self) -> bool:
        return self.total + self.next_call_ceiling > self.cap

    def persist(self) -> None:
        if self.ledger_path is None:
            return
        ledger = {
            "cap_usd": self.cap,
            "total_usd": round(self.total, 6),
            "openrouter_measured_usd": round(self.or_measured, 6),
            "openrouter_estimate_since_checkpoint_usd": round(self.or_estimate_since_checkpoint, 6),
            "deepseek_estimate_usd": round(self.ds_estimate, 6),
            "calls": self.calls,
            "checkpoints": self.checkpoints,
            "measured_checkpoints": self.measured_checkpoints,
            "method": "measured+estimate" if self.start_usage is not None else "estimate_only",
            "next_call_ceiling_usd": round(self.next_call_ceiling, 6),
            "updated": _iso_z(dt.datetime.now(dt.timezone.utc)),
        }
        self.ledger_path.parent.mkdir(parents=True, exist_ok=True)
        tmp = self.ledger_path.with_suffix(self.ledger_path.suffix + ".tmp")
        tmp.write_bytes(json.dumps(ledger, indent=2).encode("utf-8"))
        os.replace(tmp, self.ledger_path)


# ---------------------------------------------------------------------------
# Classify phase
# ---------------------------------------------------------------------------

EXIT_OK = 0
EXIT_ERROR = 1
EXIT_CAP = 3
EXIT_EXHAUSTED = 4
EXIT_STRATUM = 5


def run_classify(
    rows: list[dict],
    cache_path: pathlib.Path,
    router,
    meter: SpendMeter,
    *,
    limit: int | None = None,
    now_fn: Callable[[], dt.datetime] = lambda: dt.datetime.now(dt.timezone.utc),
) -> int:
    """Classify every selected row without a final cached outcome, in selection order.

    BF-04: no per-run time budget — the 1200 s G-09 budget protects the 30-min
    Actions job; this local tool has no such limit (3,695 ms/item measured for
    DeepSeek at gate R1 → 1200 s would cover only ~325 items).
    """
    from pipeline.news.feeds import strip_html

    router.budget_s = float("inf")

    cache = load_cache(cache_path)
    todo = [r for r in rows if not _is_final(cache.get(r["id"]))]
    if limit is not None:
        todo = todo[:limit]
    logger.info("classify: %d selected, %d to attempt", len(rows), len(todo))

    cache_path.parent.mkdir(parents=True, exist_ok=True)
    last_written: dict[str, object] = {}
    with open(cache_path, "a", encoding="utf-8", newline="") as fh:

        def _write(key: str, res) -> None:
            fh.write(json.dumps(_cache_line(key, res, now_fn()), ensure_ascii=False) + "\n")
            fh.flush()
            last_written[key] = res

        for n, row in enumerate(todo, 1):
            if meter.would_exceed():
                logger.warning(
                    "classify: spend cap %.4f reached (total %.4f) — stopping, exit 3",
                    meter.cap, meter.total,
                )
                return EXIT_CAP
            # FID-06: the stored raw description carries HTML entities (2,782/4,427
            # rows) — hand the classifier the same entity-free text as the live path.
            res = router.classify(row["title"] or "", strip_html(row["description"] or ""),
                                  key=row["id"])
            if res is None:
                logger.error("classify: router exhausted after %d attempts — exit 4", n - 1)
                return EXIT_EXHAUSTED
            _write(row["id"], res)
            meter.charge(res)
            # NB-06: a breaker trip re-dispatched the tripping streak to the backup;
            # one cache line per (key, result) supersedes that key's API_ERROR line.
            for rkey, rres in router.pop_redispatched():
                if not rkey:
                    continue
                already = last_written.get(rkey) is rres
                _write(rkey, rres)
                if not already:
                    meter.charge(rres)
            if n % 100 == 0:
                logger.info("classify: %d/%d, spend %.4f", n, len(todo), meter.total)
    meter.persist()
    return EXIT_OK


# ---------------------------------------------------------------------------
# Apply phase
# ---------------------------------------------------------------------------

def _load_json(path: pathlib.Path) -> dict:
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    return data if isinstance(data, dict) else {}


def _incidents(path: pathlib.Path) -> list[dict]:
    return list(_load_json(path).get("incidents") or [])


def _raw_lni(current_path: pathlib.Path):
    """last_new_incident_at as stored (sentinel "<absent>" when the key is missing)."""
    data = _load_json(current_path)
    return data.get("last_new_incident_at", "<absent>")


def run_apply(
    data_dir: pathlib.Path,
    cache_path: pathlib.Path,
    *,
    since: dt.datetime,
    exclude_ids: set[str],
    withhold_ids: set[str],
    today: dt.date,
    now: dt.datetime,
    spend_ledger: pathlib.Path | None = None,
) -> tuple[int, dict]:
    from pipeline.news import centroids, dedup, resolver, store
    from pipeline.news.feeds import source_headline
    from pipeline.news.fidelity import forbidden_term, guard_title_en
    from pipeline.news.schema import ClassifierOutput, IncidentRecord
    from pydantic import ValidationError

    current_path = data_dir / "current.json"
    archive_dir = data_dir / "archive"
    cutoff = today - dt.timedelta(days=WINDOW_DAYS)

    scanned = _scan(data_dir, since)
    rows = sorted((row for _, row in scanned), key=_order_key)
    cache = load_cache(cache_path)

    lni_before = _raw_lni(current_path)

    stage_of: dict[str, tuple[str, str]] = {}  # id -> (stage, reclassified_model)
    candidates: list[dict] = []
    cand_meta: dict[int, tuple[str, str]] = {}  # id(incident) -> (row id, model label)
    api_error_breakdown: Counter = Counter()
    counts = Counter()

    for row in rows:
        rid = row["id"]
        rec = cache.get(rid)
        model_label = f"{rec.get('provider')}:{rec.get('model')}" if rec else "manual"
        if rid in exclude_ids:
            stage_of[rid] = ("manual_exclusion", model_label)
            counts["excluded"] += 1
            continue
        if rid in withhold_ids:
            counts["withheld"] += 1
            continue
        if rec is None:
            counts["not_attempted"] += 1
            continue
        outcome = rec.get("outcome")
        if outcome == API_ERROR or outcome not in FINAL_OUTCOMES:
            counts["api_error_remaining"] += 1
            err = rec.get("error")
            api_error_breakdown[err if err in ("empty_content", "finish_length") else "other"] += 1
            continue
        if outcome == "not_crime":
            stage_of[rid] = ("low_confidence", model_label)
            continue
        if outcome == "parse_error":
            stage_of[rid] = ("parse_error", model_label)
            continue
        # OK → the scrape_news.py OK path: resolve_cut → get_centroid → build_incident.
        try:
            out = ClassifierOutput.model_validate(rec.get("output") or {})
        except ValidationError:
            stage_of[rid] = ("parse_error", model_label)
            continue
        resolved = resolver.resolve_cut(out.commune_name, out.region_hint) if out.commune_name else None
        if resolved is None:
            stage_of[rid] = ("commune_null" if not out.commune_name else "resolver_fail", model_label)
            continue
        cut, slug = resolved
        centroid = centroids.get_centroid(cut)
        if centroid is None:
            stage_of[rid] = ("centroid_fail", model_label)
            continue
        lat, lng = centroid
        # FID-01 (G-28): the outlet's verbatim headline is the stored Spanish
        # headline; the classifier's title_en passes the kinship guard (FID-07).
        outlet = row.get("outlet") or ""
        title_src = source_headline(row.get("title") or "", outlet)
        if not title_src.strip():
            # Pre-push F-1: build_incident raises on an empty title_src — reject
            # this row only instead of aborting the whole apply.
            stage_of[rid] = ("empty_title", model_label)
            continue
        title_en, fell_back = guard_title_en(title_src, out.title_en, outlet)
        if forbidden_term(title_src) or forbidden_term(title_en):
            stage_of[rid] = ("editorial_filter", model_label)  # G-29
            counts["editorial_filtered"] += 1
            continue
        if fell_back:
            counts["title_en_fallbacks"] += 1
        incident = store.build_incident(
            url=row["url"], cut=cut, lat=lat, lng=lng,
            title_src=title_src, title_en=title_en,
            date=row.get("date") or "", outlet=outlet,
            family=out.family, slug=slug,
        )
        if incident is None:
            stage_of[rid] = ("url_rejected", model_label)
            continue
        # merge_and_write validates the WHOLE payload and silently skips the write
        # on any invalid record — pre-validate each candidate so one bad row cannot
        # block the batch.
        try:
            IncidentRecord.model_validate(incident)
            if _parse_date(incident["date"]) is None:
                raise ValueError("date")
        except (ValidationError, ValueError):
            stage_of[rid] = ("invalid_record", model_label)
            continue
        candidates.append(incident)
        cand_meta[id(incident)] = (rid, model_label)

    # Dedup against EXISTING incidents first (existing wins): current.json plus every
    # archive month a candidate would age into.
    existing = _incidents(current_path)
    months = sorted({c["date"][:7] for c in candidates if _parse_date(c["date"]) < cutoff})
    for month in months:
        existing += _incidents(archive_dir / f"{month}.json")
    # Full id set across current + ALL archive months (idempotent recovery: an id
    # already published — e.g. a crash between merge and the rejected rewrite — is
    # counted as already_present and removed from rejected/, never merged twice).
    all_ids = {inc.get("id") for inc in _incidents(current_path)}
    if archive_dir.is_dir():
        for month_path in archive_dir.glob("*.json"):
            all_ids |= {inc.get("id") for inc in _incidents(month_path)}

    already_present = [c for c in candidates if c["id"] in all_ids]
    fresh = [c for c in candidates if c["id"] not in all_ids]
    survivors = dedup.deduplicate(existing + fresh)  # existing first → existing wins
    survivor_objs = {id(x) for x in survivors}
    accepted: list[dict] = []
    for c in fresh:
        if id(c) in survivor_objs:
            accepted.append(c)
        else:
            row_id, model_label = cand_meta[id(c)]
            stage_of[row_id] = ("dedup_duplicate", model_label)

    accepted_in_window = sum(1 for c in accepted if _parse_date(c["date"]) >= cutoff)
    accepted_archived = len(accepted) - accepted_in_window

    if accepted:
        with _store_writes_preserve_eol():
            store.merge_and_write(
                accepted, current_path, archive_dir,
                window_days=WINDOW_DAYS, today=today, now=now,
                bump_last_new=False,  # G-07(a) / R-02: only live runs refresh G-05 evidence
            )
        # merge_and_write logs and skips the write on a validation failure — verify.
        written = {inc.get("id") for inc in _incidents(current_path)}
        for month in {c["date"][:7] for c in accepted}:
            written |= {inc.get("id") for inc in _incidents(archive_dir / f"{month}.json")}
        missing = [c["id"] for c in accepted if c["id"] not in written]
        if missing:
            logger.error("apply: %d accepted ids not written (merge validation?) — "
                         "rejected/ left untouched", len(missing))
            return EXIT_ERROR, {"error": "merge_not_written", "missing": missing[:20]}

    lni_after = _raw_lni(current_path)
    if lni_after != lni_before:
        logger.error("apply: last_new_incident_at changed (%r -> %r) — G-07(a) violated",
                     lni_before, lni_after)
        return EXIT_ERROR, {"error": "last_new_incident_at_changed"}

    # Row ids (== make_id(url) in real data, but never assumed).
    removed_ids = {cand_meta[id(c)][0] for c in accepted + already_present}
    _rewrite_rejected(data_dir, since, removed_ids, stage_of, now)

    by_stage = Counter(stage for stage, _ in stage_of.values())
    frozen_ids = {r["id"] for r in rows if _frozen(r)}
    resolved_ids = removed_ids | set(stage_of)
    spend = None
    if spend_ledger is not None and spend_ledger.exists():
        spend = json.loads(spend_ledger.read_text(encoding="utf-8")).get("total_usd")
    by_file = Counter(name for name, _ in scanned)
    report = {
        "selected": len(rows),
        "by_file": dict(sorted(by_file.items())),
        "frozen_subset": len(frozen_ids),
        "frozen_subset_resolved": len(frozen_ids & resolved_ids),
        "accepted_in_window": accepted_in_window,
        "accepted_archived": accepted_archived,
        "already_present": len(already_present),
        "by_stage": dict(sorted(by_stage.items())),
        "api_error_remaining": counts["api_error_remaining"],
        "api_error_breakdown": {k: api_error_breakdown.get(k, 0)
                                for k in ("empty_content", "finish_length", "other")},
        "not_attempted": counts["not_attempted"],
        "withheld": counts["withheld"],
        "excluded": counts["excluded"],
        "fidelity": {"title_en_fallbacks": counts["title_en_fallbacks"],
                     "editorial_filtered": counts["editorial_filtered"]},
        "spend_usd": spend,
        "window_cutoff": cutoff.isoformat(),
        "last_new_incident_at_before": None if lni_before == "<absent>" else lni_before,
        "last_new_incident_at_after": None if lni_after == "<absent>" else lni_after,
    }
    return EXIT_OK, report


def _rewrite_rejected(
    data_dir: pathlib.Path,
    since: dt.datetime,
    removed_ids: set[str],
    stage_of: dict[str, tuple[str, str]],
    now: dt.datetime,
) -> None:
    """Rewrite each touched month file in place: drop accepted ids, set the real stage
    on the others (key order preserved, reclassified_* appended), leave API_ERROR /
    uncached / withheld rows byte-equal. A file with no change is not written."""
    stamp = _iso_z(now)
    for path in _month_files(data_dir, since):
        envelope = _load_envelope(path)
        changed = False
        new_items = []
        for row in envelope["items"]:
            if isinstance(row, dict) and _is_selected(row, since):
                rid = row.get("id")
                if rid in removed_ids:
                    changed = True
                    continue
                if rid in stage_of:
                    stage, model_label = stage_of[rid]
                    row = dict(row)
                    row["rejection_stage"] = stage
                    row["reclassified_at"] = stamp
                    row["reclassified_model"] = model_label
                    changed = True
            new_items.append(row)
        if not changed:
            continue
        envelope["items"] = new_items
        envelope["generated"] = now.astimezone(dt.timezone.utc).isoformat()
        eol_preserving_write_json(path, envelope)
        logger.info("apply: rewrote %s", path.name)


# ---------------------------------------------------------------------------
# Review / audit sample (R-06, G-11, G-14, BF-03)
# ---------------------------------------------------------------------------

def _ok_items(rows: list[dict], cache: dict[str, dict]) -> list[tuple[dict, dict]]:
    return [(r, cache[r["id"]]) for r in rows
            if cache.get(r["id"], {}).get("outcome") == "ok" and cache[r["id"]].get("output")]


def _published_headlines(row: dict, output: dict) -> dict:
    """What run_apply would publish (premortem R-16): the outlet's verbatim headline
    (title_src) and the guarded title_en — never the classifier's title_es."""
    from pipeline.news.feeds import source_headline
    from pipeline.news.fidelity import guard_title_en

    outlet = row.get("outlet") or ""
    title_src = source_headline(row.get("title") or "", outlet)
    title_en, fell_back = guard_title_en(title_src, output.get("title_en"), outlet)
    return {"title_src": title_src, "title_en": title_en, "title_en_fallback": fell_back}


def run_review(rows: list[dict], cache: dict[str, dict], out=None) -> int:
    out = out or sys.stdout
    hits = 0
    for row, rec in _ok_items(rows, cache):
        output = rec["output"]
        shown = _published_headlines(row, output)
        text = " ".join([row.get("title") or "", row.get("description") or "",
                         shown["title_src"]])
        if REVIEW_RE.search(text):
            hits += 1
            print(json.dumps({
                "id": row["id"], "date": row.get("date"), "family": output.get("family"),
                **shown, "source_title": row.get("title"),
            }, ensure_ascii=False), file=out)
    print(f"review_hits={hits}", file=out)
    return EXIT_OK


def stratum_of(row: dict) -> str:
    host = (urlparse(row.get("url") or "").hostname or "").lower()
    if host == "news.google.com":
        return STRATUM_GNEWS
    if NON_CHILE_RE.search(row.get("title") or "") or NON_CHILE_RE.search(row.get("description") or ""):
        return STRATUM_NON_CHILE
    return STRATUM_RANDOM


def run_audit_sample(
    rows: list[dict],
    cache: dict[str, dict],
    n: int,
    seed: int,
    out_path: pathlib.Path,
    *,
    exclude_ids: set[str] = frozenset(),
    withhold_ids: set[str] = frozenset(),
    out=None,
) -> int:
    from pipeline.news import resolver

    out = out or sys.stdout

    ok = [(r, c) for r, c in _ok_items(rows, cache) if r["id"] not in exclude_ids]
    by_stratum: dict[str, list[tuple[dict, dict]]] = {s: [] for s in STRATA}
    for r, c in ok:
        by_stratum[stratum_of(r)].append((r, c))

    # BF-03: a DEFINED stratum with 0 candidates (before withholding) → exit 5.
    empty = [s for s in STRATA if not by_stratum[s]]
    for s in STRATA:
        print(f"stratum {s}: cached_ok={len(by_stratum[s])}", file=out)
    if empty:
        print(f"stratum definition broken: 0 candidates in {', '.join(empty)} — exit 5", file=out)
        return EXIT_STRATUM

    pools = {s: sorted((p for p in by_stratum[s] if p[0]["id"] not in withhold_ids),
                       key=lambda p: p[0]["id"]) for s in STRATA}
    quotas = {STRATUM_GNEWS: math.ceil(0.4 * n), STRATUM_NON_CHILE: math.ceil(0.2 * n)}
    quotas[STRATUM_RANDOM] = max(0, n - quotas[STRATUM_GNEWS] - quotas[STRATUM_NON_CHILE])

    rng = random.Random(seed)
    sample: list[tuple[str, dict, dict]] = []
    shortfall = 0
    for s in (STRATUM_GNEWS, STRATUM_NON_CHILE):
        pool = pools[s]
        take = min(quotas[s], len(pool))
        if take < quotas[s]:
            shortfall += quotas[s] - take
            print(f"shortfall {s}: quota={quotas[s]} available={len(pool)} "
                  f"(filled from {STRATUM_RANDOM})", file=out)
        picked = rng.sample(pool, take)
        sample += [(s, r, c) for r, c in picked]
    rand_pool = pools[STRATUM_RANDOM]
    want = quotas[STRATUM_RANDOM] + shortfall
    take = min(want, len(rand_pool))
    if take < want:
        print(f"shortfall {STRATUM_RANDOM}: wanted={want} available={len(rand_pool)} "
              f"(sample has {len(sample) + take} of {n})", file=out)
    sample += [(STRATUM_RANDOM, r, c) for r, c in rng.sample(rand_pool, take)]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines = []
    for s, r, c in sample:
        o = c["output"]
        resolved = resolver.resolve_cut(o.get("commune_name"), o.get("region_hint")) \
            if o.get("commune_name") else None
        lines.append(json.dumps({
            "id": r["id"], "stratum": s,
            "title": r.get("title"), "description": r.get("description"),
            "url": r.get("url"), "outlet": r.get("outlet"), "date": r.get("date"),
            "output": {
                "commune_name": o.get("commune_name"), "region_hint": o.get("region_hint"),
                "cut": resolved[0] if resolved else None,
                "slug": resolved[1] if resolved else None,
                "family": o.get("family"), **_published_headlines(r, o),
                "confidence": o.get("confidence"),
            },
            "model": f"{c.get('provider')}:{c.get('model')}",
        }, ensure_ascii=False))
    out_path.write_bytes(("\n".join(lines) + ("\n" if lines else "")).encode("utf-8"))
    counts = Counter(s for s, _, _ in sample)
    for s in STRATA:
        print(f"sampled {s}={counts.get(s, 0)}", file=out)
    print(f"sampled_total={len(sample)} seed={seed} out={out_path}", file=out)
    return EXIT_OK


# ---------------------------------------------------------------------------
# Dry run
# ---------------------------------------------------------------------------

def run_dry(data_dir: pathlib.Path, since: dt.datetime, cache_path: pathlib.Path,
            today: dt.date, out=None) -> int:
    out = out or sys.stdout
    scanned = _scan(data_dir, since)
    rows = [row for _, row in scanned]
    cache = load_cache(cache_path)  # read-only; never created
    cutoff = today - dt.timedelta(days=WINDOW_DAYS)
    by_file = Counter(name for name, _ in scanned)
    by_day = Counter((parse_dt(r["first_seen"]).date().isoformat()) for r in rows)
    by_pub_month = Counter((r.get("date") or "")[:7] or "?" for r in rows)
    dates = sorted(d for d in (_parse_date(r.get("date")) for r in rows) if d)
    priority_days = Counter(r["date"] for r in rows
                            if (d := _parse_date(r.get("date"))) and PRIORITY_START <= d <= PRIORITY_END)
    already = sum(1 for r in rows if _is_final(cache.get(r["id"])))
    cached_api_error = sum(1 for r in rows
                           if cache.get(r["id"]) and not _is_final(cache.get(r["id"])))
    would_archive = sum(1 for r in rows if (d := _parse_date(r.get("date"))) and d < cutoff)
    print(f"selected={len(rows)}", file=out)
    print(f"by_file={json.dumps(dict(sorted(by_file.items())))}", file=out)
    print(f"frozen_subset={sum(1 for r in rows if _frozen(r))}", file=out)
    print(f"by_first_seen_day={json.dumps(dict(sorted(by_day.items())))}", file=out)
    print(f"by_pub_month={json.dumps(dict(sorted(by_pub_month.items())))}", file=out)
    print(f"priority_days_{PRIORITY_START}..{PRIORITY_END}={json.dumps(dict(sorted(priority_days.items())))}", file=out)
    print(f"date_range={dates[0] if dates else None}..{dates[-1] if dates else None}", file=out)
    print(f"window_cutoff={cutoff}", file=out)
    print(f"would_archive={would_archive}", file=out)
    print(f"already_cached={already}", file=out)
    print(f"cached_api_error={cached_api_error}", file=out)
    print(f"planned_calls={len(rows) - already}", file=out)
    return EXIT_OK


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="NREC-09 backfill of the Sept-2026 classifier outage")
    mode = p.add_mutually_exclusive_group(required=True)
    mode.add_argument("--dry-run", action="store_true", help="counts only, zero writes")
    mode.add_argument("--classify", action="store_true", help="classify into --cache (no data/ writes)")
    mode.add_argument("--apply", action="store_true", help="apply --cache to data/incidents")
    mode.add_argument("--review", action="store_true", help="print R-06 regex hits among cached OK")
    mode.add_argument("--audit-sample", type=int, metavar="N", help="G-11 stratified sample of cached OK")
    p.add_argument("--data-dir", type=pathlib.Path, default=DEFAULT_DATA_DIR)
    p.add_argument("--since", default=DEFAULT_SINCE)
    p.add_argument("--cache", type=pathlib.Path, required=True, help="JSONL cache, outside data/")
    p.add_argument("--limit", type=int, default=None)
    p.add_argument("--exclude-ids", default="", help="ID[,ID] → stage manual_exclusion")
    p.add_argument("--withhold-ids", type=pathlib.Path, default=None,
                   help="file, one id per line → left untouched (G-11/G-14)")
    p.add_argument("--spend-cap", type=float, default=None, help="USD, G-11: 5.00 − A/B spend − 0.25")
    p.add_argument("--spend-ledger", type=pathlib.Path, default=None)
    p.add_argument("--report", type=pathlib.Path, default=None)
    p.add_argument("--seed", type=int, default=3405)
    p.add_argument("--out", type=pathlib.Path, default=None)
    p.add_argument("--today", default=None, help="YYYY-MM-DD (window reference; default today)")
    return p


def _load_env_files(env_files: Iterable[pathlib.Path]) -> None:
    try:
        from dotenv import load_dotenv
    except ImportError:
        logger.warning("python-dotenv not installed — relying on the process env")
        return
    for f in env_files:
        if f.exists():
            load_dotenv(dotenv_path=f, override=False)


def main(
    argv: list[str] | None = None,
    *,
    env_files: Iterable[pathlib.Path] | None = None,
    router_hook: Callable | None = None,
    http_get: Callable | None = None,
) -> int:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    args = _build_parser().parse_args(argv)

    data_dir: pathlib.Path = args.data_dir
    since = parse_dt(args.since)
    if since is None:
        print(f"ERROR: invalid --since {args.since!r}", file=sys.stderr)
        return EXIT_ERROR
    today = dt.date.fromisoformat(args.today) if args.today else dt.date.today()
    for path, flag in ((args.cache, "--cache"), (args.spend_ledger, "--spend-ledger"),
                       (args.report, "--report"), (args.out, "--out")):
        _assert_outside(path, data_dir, flag)
    if not (data_dir / "rejected").is_dir():
        print(f"ERROR: {data_dir}/rejected not found", file=sys.stderr)
        return EXIT_ERROR

    exclude_ids = _split_ids(args.exclude_ids)
    withhold_ids = _read_ids_file(args.withhold_ids)

    if args.dry_run:
        return run_dry(data_dir, since, args.cache, today)

    if args.review:
        return run_review(select_outage_rows(data_dir, since), load_cache(args.cache))

    if args.audit_sample is not None:
        if args.out is None:
            print("ERROR: --audit-sample needs --out", file=sys.stderr)
            return EXIT_ERROR
        return run_audit_sample(
            select_outage_rows(data_dir, since), load_cache(args.cache),
            args.audit_sample, args.seed, args.out,
            exclude_ids=exclude_ids, withhold_ids=withhold_ids,
        )

    if args.apply:
        code, report = run_apply(
            data_dir, args.cache, since=since, exclude_ids=exclude_ids,
            withhold_ids=withhold_ids, today=today,
            now=dt.datetime.now(dt.timezone.utc), spend_ledger=args.spend_ledger,
        )
        text = json.dumps(report, indent=2, ensure_ascii=False)
        print(text)
        if args.report is not None:
            args.report.parent.mkdir(parents=True, exist_ok=True)
            args.report.write_bytes((text + "\n").encode("utf-8"))
        return code

    # --classify
    if args.spend_cap is None:
        print("ERROR: --classify needs --spend-cap (G-11)", file=sys.stderr)
        return EXIT_ERROR
    rows = select_outage_rows(data_dir, since)
    cache = load_cache(args.cache)
    pending = [r for r in rows if not _is_final(cache.get(r["id"]))]
    if args.limit is not None:
        pending = pending[: args.limit]
    if not pending:
        print("classify: nothing to do (every selected id has a final cached outcome)")
        return EXIT_OK

    # R-12: keys from pipeline/.env then the repo-root .env (override=False), and only
    # THEN import the classifier — its import-time client reads os.environ.
    _load_env_files(env_files if env_files is not None
                    else [_REPO_ROOT / "pipeline" / ".env", _REPO_ROOT / ".env"])
    from pipeline.news.classifier import build_router_from_env

    router = build_router_from_env()
    if router_hook is not None:
        router_hook(router)
    if not router.any_key_present:
        print(f"ERROR: no API key ({' / '.join(router.key_env_names)})", file=sys.stderr)
        return EXIT_ERROR
    logger.info("classify: primary=%s backup=%s", router.primary_label, router.backup_label)
    router.preflight()

    ledger = args.spend_ledger or args.cache.with_name(args.cache.stem + ".spend.json")
    _assert_outside(ledger, data_dir, "--spend-ledger")
    meter = SpendMeter(
        args.spend_cap, ledger,
        api_key=os.environ.get("OPENROUTER_API_KEY", "").strip() or None,
        http_get=http_get,
    )
    meter.start()
    code = run_classify(rows, args.cache, router, meter, limit=args.limit)
    final_cache = load_cache(args.cache)
    print(f"exit={code} spend_usd={meter.total:.6f} cap={meter.cap} "
          f"cached_final={sum(1 for r in rows if _is_final(final_cache.get(r['id'])))} "
          f"cached_api_error={sum(1 for r in rows if final_cache.get(r['id']) and not _is_final(final_cache.get(r['id'])))} "
          f"uncached={sum(1 for r in rows if r['id'] not in final_cache)} "
          f"failovers={router.failovers}")
    return code


if __name__ == "__main__":
    sys.exit(main())
